### PR TITLE
enable lambda sync for CHOP bucket

### PR DESCRIPTION
**Pull request by clarisse-lau**
Setting up the lambda sync function for the HTAN CHOP bucket

### CODE REVIEW

**Review by zaro0508 — APPROVED** [review]

**Review by BrunoGrandePhD — COMMENTED** [review]
I don't have context on this PR, so I can't really approve it. I defer to @clarisse-lau. 

@clarisse-lau Out of curiosity, were notifications not enabled yet for the CHOP bucket because of an accidental omission?

**Comment by clarisse-lau** [comment]
They weren't enabled because thus far CHOP has only been uploading data to Synapse, making the sync function unnecessary

**Comment by clarisse-lau** [comment]
Hi @zaro0508 @BrunoGrandePhD- if this looks ok, can we merge?

**Review by BrunoGrandePhD — APPROVED** [review]

**Comment by adamjtaylor** [comment]
@zaro0508 @BrunoGrandePhD Is this now able to be merged? This is being setup to help with [HTAN-161](https://sagebionetworks.jira.com/browse/HTAN-161) in which we need to move and remediate some of CHOPs data.

**Pull request merged**
