### PR TITLE
request t3.medium EC2 for wpoehlm

### PR DESCRIPTION
**Pull request by wpoehlm**

### CODE REVIEW

**Comment by zaro0508** [comment]
Added support for a1 instance in PR https://github.com/Sage-Bionetworks/aws-infra/pull/130
We'll need to merge that before accepting this PR.  Hold tight.

**Comment by wpoehlm** [comment]
> 
> 
> Added support for a1 instance in PR [Sage-Bionetworks/aws-infra#130](https://github.com/Sage-Bionetworks/aws-infra/pull/130)
> We'll need to merge that before accepting this PR. Hold tight.

No rush, thanks!

**Comment by zaro0508** [comment]
a1 instances only works with Arm based AMIs.  I was hoping that it would just work with our deployment system however that doesn't seem to be the case.  It will require some (maybe lots?) debugging to get Arm to work.  For now, would it be possible to using one of the t3 instances instead?

**Comment by wpoehlm** [comment]
> 
> 
> a1 instances only works with Arm based AMIs. I was hoping that it would just work with our deployment system however that doesn't seem to be the case. It will require some (maybe lots?) debugging to get Arm to work. For now, would it be possible to use one of the t3 instances instead?

Changed to t3.medium

**Pull request merged**
