### PR TITLE
create htan synapse sync bucket

### PR DESCRIPTION
**Pull request by clarisse-lau**
Create new HTAN bucket

### CODE REVIEW

**Comment by clarisse-lau** [comment]
@zaro0508 @xdoan please review

**Comment by zaro0508** [comment]
you might want to do up a PR to remove "s3-synapse-sync-bucket-a" @clarisse-lau.  Just delete the file to remove the bucket.

**Comment by clarisse-lau** [comment]
@zaro0508 done: https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/386

**Comment by zaro0508** [comment]
now you'll need a PR with EnableNotificationConfiguration set to "true" @clarisse-lau

**Pull request merged**
