### PR TITLE
Enable Stanford S3 bucket notifs

### PR DESCRIPTION
**Pull request by clarisse-lau**
Configuring the HTAN Stanford bucket with synapse sync lambda, and granting access to collaborator Daniel Cotter

### CODE REVIEW

**Comment by BrunoGrandePhD** [comment]
@clarisse-lau: Out of curiosity, why was this PR closed? I wasn't yet involved in this discussion until afterwards, so I want to make sure I understand the context behind the decision in case I don't have the full picture.

**Comment by clarisse-lau** [comment]
@BrunoGrandePhD No, thanks for reopening. 
I may be the one without the full picture, as we haven’t yet had a discussion re: Globus at the DCC calls. I had closed it because with the resolution of the Jira ticket, it seemed that this required a larger DCC/SC discussion and we'd be holding off until that occurred; I wasn’t aware you were already spec-ing out requirements for use with the HTAN buckets

**Comment by BrunoGrandePhD** [comment]
I think your instinct with this PR was correct. I don't think a larger DCC/SC discussion needs to happen in this case because the Globus S3 connector appears to act like any other S3 client (_e.g._ the AWS CLI). It remains to be confirmed whether it will work as such, but if that's indeed the case, I think this PR might be enough to grant them access to the bucket. 

Let's wait for Karl to confirm that they will follow the instructions that I laid out in my email before merging this though.

**Review by BrunoGrandePhD — APPROVED** [review]
With Karl's email, I think we can proceed with merging this PR. 

@zaro0508: Review, please? Thanks!

**Review by zaro0508 — APPROVED** [review]

**Pull request merged**
