### PR TITLE
Request general user access to htan s3 buckets.

### PR DESCRIPTION
**Pull request by hweej**
Hi hello, I'm requesting general user access to all of the HTAN s3 buckets.
I currently have the `sandbox-developer` role.

Please let me know if I've done anything incorrectly.

### CODE REVIEW

**Comment by hweej** [comment]
tagged! @BrunoGrandePhD

**Review by BrunoGrandePhD — APPROVED** [review]
Thanks for tagging me, @hweej! 

@zaro0508: For context, Jason recently joined James' team and is working on HTAN. This PR is intended to grant him access to the HTAN buckets.

**Review by zaro0508 — APPROVED** [review]
I hope these users were created with CFN and not point and click.

**Comment by BrunoGrandePhD** [comment]
@zaro0508: This PR has been updated to use the new JumpCloud assumed-role session ARNs.

**Review by zaro0508 — APPROVED** [review]
LGTM, i think you'll like this better than the service user route.

**Comment by BrunoGrandePhD** [comment]
@clarisse-lau: Does this look good to you? I just wanted to make sure you're in the loop. We're granting Jason with the same access as Dave.

**Review by clarisse-lau — APPROVED** [review]
looks good!

**Pull request merged**
