### PR TITLE
remove milen's EC2s

### PR DESCRIPTION
**Pull request by zaro0508**

### CODE REVIEW

**Comment by thomasyu888** [comment]
LGTM, but I dont work on any of these instances so would need Milen's final approval to remove these.

**Review by xschildw — APPROVED** [review]
Pending Milen's OK by Tom's comment.

**Comment by zaro0508** [comment]
are we ready to remove these instances @milen-sage ?

**Comment by milen-sage** [comment]
not yet - we will have a meeting next week to discuss an updated setup for the miniDREAM program, which will determine to what extent we are reusing components of previous instances; most of these components should be living in gh repos, but we want to comnfim we have everything we needed out of the instances before removing.

**Comment by zaro0508** [comment]
ping @milen-sage, are you ready to approve this PR yet?

**Comment by milen-sage** [comment]
Thanks for the reminder @zaro0508 ! We are still scoping out the work for this year's miniDREAM course. If it's not a problem, could we hold on to the instance over the next couple of weeks.

**Comment by zaro0508** [comment]
ping @milen-sage, are you ready to approve this PR yet?

**Comment by milen-sage** [comment]
feel free to remove these instances.

**Pull request merged**
